apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kestra-data
  namespace: enlight-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kestra-db
  namespace: enlight-platform
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
