apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: enlight-demo-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/kirtiprasadranasingh/Devops-localstack.git
    targetRevision: main
    path: oke/gitops/apps/fastapi-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: enlight-staging
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
